import { isNight } from './chronicle';
import { placeName } from './landmarks';
import { INTELLIGENT_SPECIES } from './species';
import type { IntelligentSpeciesId, MaterialId, Settler, World } from './types';
import { MATERIALS, RECIPE_BY_ID } from './fabrication';

/**
 * Deterministic contextual dialogue. Lines are *derived* from live simulation
 * state — species, personality, current goal, needs, relationship with
 * Kai, recent memory, place, time and weather — never authored per
 * character and never generated by an external model.
 *
 * This is a proof of social presence, not a dialogue RPG: 1-3 short lines.
 */

export interface DialogueLine {
  speaker: string;
  text: string;
}

export interface DialogueExchange {
  settlerId: string;
  name: string;
  speciesLabel: string;
  /** Relationship with Kai after this exchange. */
  affinity: number;
  firstMeeting: boolean;
  lines: DialogueLine[];
}

/** Greeting shaped by how well this settler already knows Kai. */
function greetingLine(s: Settler, affinity: number, firstMeeting: boolean): string {
  if (firstMeeting) {
    switch (s.speciesId as IntelligentSpeciesId) {
      case 'veyra':
        return `You are the one who came down alone. I am ${s.name}. We wondered when you would walk over.`;
      case 'caelari':
        return `So the solitary lander speaks after all. ${s.name}. Use the name, not the species.`;
      default:
        return `I don't think we've spoken. ${s.name}. You're the one from the drop pod.`;
    }
  }
  if (affinity >= 30) return `Good to see you, Kai.`;
  if (affinity >= 10) return `Kai. You're still wandering, I see.`;
  if (affinity <= -10) return `I don't have much to say right now.`;
  if (s.personality.caution > 0.65) return `You move quietly for someone so tall.`;
  return `Kai.`;
}

/** The settler's current business, in their own words. */
function goalLine(s: Settler, world: World): string | null {
  const g = s.goal;
  const here = placeName(s.pos);
  switch (g.type) {
    case 'eat': {
      const where = g.targetPos ? placeName(g.targetPos) : 'a patch I know';
      if (s.hunger > 70) return `I'm hungry. I was heading for ${where} — supplies are thinner than I expected.`;
      return `I was going to eat at ${where} before the light turns.`;
    }
    case 'rest':
      return s.energy < 25
        ? `I've been on my feet since we landed. I need to lie down.`
        : `I was about to rest. Nothing urgent.`;
    case 'explore': {
      if (g.label === 'Forage for food') return `I don't know where the food grows yet. I'm looking.`;
      if (s.personality.curiosity > 0.6) return `I've been mapping ${here}. There's something worth seeing past the treeline.`;
      return `Walking the ground near ${here}. Learning it.`;
    }
    case 'socialize': {
      const other = world.settlers.find((o) => o.id === g.targetId);
      return other ? `I was on my way to find ${other.name}.` : `I was looking for company.`;
    }
    case 'talk-emerson':
    case 'idle':
      return null;
    default:
      return null;
  }
}

/** An opinion, worry or observation drawn from needs, memory and world state. */
function colorLine(s: Settler, world: World, affinity: number): string | null {
  const recent = s.memories[s.memories.length - 1];
  const speciesDef = INTELLIGENT_SPECIES[s.speciesId as IntelligentSpeciesId];

  // Strong needs speak loudest.
  if (s.hunger > 82) return `We counted on finding more to eat than this.`;
  if (s.energy < 20) return `None of us have slept properly on this world yet.`;
  if (s.needs.social > 70 && s.personality.sociability > 0.55) {
    return `Everyone scattered so fast after we landed. I don't like how quiet it is.`;
  }

  // Weather and time.
  if (world.weather === 'mist' && s.personality.caution > 0.5) {
    return `I don't like this mist. You can't see what's coming through it.`;
  }
  if (isNight(world.timeSec)) {
    return s.personality.caution > 0.6
      ? `The plants glow brighter at night. I can't decide if that's beautiful or a warning.`
      : `The nights here are extraordinary. Have you looked up?`;
  }

  // Recent memory, spoken naturally.
  if (recent && world.timeSec - recent.t < 400) {
    if (recent.type === 'resource_discovered') return `I found something useful: ${recent.place}.`;
    if (recent.type === 'social_positive' && recent.subjectName) {
      return `I spoke with ${recent.subjectName} not long ago. It helped.`;
    }
    if (recent.type === 'social_negative' && recent.subjectName) {
      return `${recent.subjectName} and I don't agree on much. It will keep.`;
    }
    if (recent.type === 'threatened') return `Something out there took an interest in me. I'd rather it hadn't.`;
  }

  // Trusted settlers open up about their people.
  if (affinity >= 25) {
    switch (s.speciesId as IntelligentSpeciesId) {
      case 'veyra':
        return `We share what we gather. It is not generosity — it is arithmetic.`;
      case 'caelari':
        return `The others want to decide things together. I would rather decide, then explain.`;
      default:
        return `We know how to build all of it. Furnaces, wire, medicine. We just have none of it yet.`;
    }
  }

  // Species flavor for near-strangers.
  if (s.personality.curiosity > 0.7) return `Your translator works on all three of us. That still unsettles me.`;
  if (speciesDef.id === 'veyra' && s.personality.empathy > 0.6) return `If you need food, come to our hold. We keep enough.`;
  return null;
}

/**
 * Build the exchange. Pure: produces the lines and the relationship values,
 * but does not mutate the world — `playerTalk` applies the effects.
 */
/**
 * Petra's lines. Deterministic and state-aware: what she says depends on
 * whether the scanner exists yet and what Kai is actually carrying, so the
 * conversation tracks the loop without any quest bookkeeping behind it.
 */
function technicianLines(world: World, s: Settler, firstMeeting: boolean): DialogueLine[] {
  const p = world.player;
  const out: DialogueLine[] = [];
  const say = (text: string) => out.push({ speaker: s.name, text });

  if (firstMeeting) {
    say('You must be the pathfinder. Petra — I keep the Fabricator running, such as it is.');
    say(
      'The machine survived the landing. What did not survive is the supply chain behind it. It can still build almost anything, but only out of feedstock I do not have.',
    );
    say(
      'Bring me usable material and I can start rebuilding your field kit. Eden has plenty — it just is not evenly spread.',
    );
    return out;
  }

  if (!p.unlocks.scanner) {
    const scanner = RECIPE_BY_ID['scanner-mk1'];
    const missing: string[] = [];
    for (const [id, need] of Object.entries(scanner.costs)) {
      const have = p.materials[id as MaterialId];
      if (have < (need ?? 0)) missing.push(`${(need ?? 0) - have} more ${MATERIALS[id as MaterialId].name}`);
    }
    if (missing.length === 0) {
      say('That is everything the scanner needs. Load it into the hopper and I will run the sequence.');
    } else {
      say(`Still short: ${missing.join(', ')}.`);
      say(
        'Alloy is scattered all through the Riverlands — the descent shed debris the whole way down. Conductive ore is an Ashlands problem. The crystal only grows high up on the Skyreach.',
      );
    }
    return out;
  }

  // A recovered core fragment outranks anything else she has to say. She is a
  // technician looking at hardware she cannot account for, and she says so
  // plainly — nobody in EDEN explains the Sunken Ring, because nobody can.
  if (p.unlocks.capacitor && !world.flags.petraSpokeAfterCapacitor) {
    world.flags.petraSpokeAfterCapacitor = true;
    say('It took. I will be honest with you — I did not expect it to.');
    say(
      'Whatever that core is, it does not leak and it does not sag under load. I wired it into the discharge path and the blade just... accepted it, like it had been waiting for the part.',
    );
    say('I would very much like a second one. For study. Not for the blade.');
    return out;
  }

  if (p.salvage.coreFragment > 0) {
    say('That thing you brought back. I ran it through everything I have.');
    say(
      'It is not Veyra work and it is not Caelari work, and it is certainly not ours. Whatever alloy that is, we cannot make it and I cannot cut it.',
    );
    say(
      p.salvage.coreFragment > 1
        ? 'And you have more than one. So there is more than one of them still running out there. I would very much like to know what they are running for.'
        : 'It still draws power, Kai. Sitting on my bench, with nothing attached to it. Bring me another and I will keep looking.',
    );
    if (!p.unlocks.capacitor) {
      say(
        'I can do one useful thing with it, mind. Wire it into the blade as a capacitor. It will not cut deeper — it will hit like the thing on the other end owes you money.',
      );
    }
    return out;
  }

  if (!p.unlocks.arcBlade) {
    const blade = RECIPE_BY_ID['arc-blade-mk1'];
    const missing: string[] = [];
    for (const [id, need] of Object.entries(blade.costs)) {
      const have = p.materials[id as MaterialId];
      if (have < (need ?? 0)) missing.push(`${(need ?? 0) - have} more ${MATERIALS[id as MaterialId].name}`);
    }
    say('Scanner is holding calibration. Tell ARI if the resolution drifts.');
    if (missing.length === 0) {
      say(
        'And I can cut you an edge now, if you want one. I would rather you did not need it. Bring the feedstock to the hopper and I will run it.',
      );
    } else {
      say(
        'ARI has been reading things out past the Ash Pass that I do not like. If you are going that way, I can build you something to hold — an arc edge, nothing clever.',
      );
      say(`I would need ${missing.join(', ')} for it.`);
    }
    return out;
  }

  say('Scanner is holding calibration. Tell ARI if the resolution drifts.');
  say('You have the blade. Try not to make me regret building it.');
  say('Bring me more material when you find it. There is a long list of things this colony still cannot make.');
  return out;
}

export function buildExchange(world: World, s: Settler): DialogueExchange {
  const rel = s.relationships.emerson;
  const affinity = rel?.affinity ?? 0;
  const firstMeeting = !rel || rel.interactions === 0;
  const speciesDef = INTELLIGENT_SPECIES[s.speciesId as IntelligentSpeciesId];

  // The fabrication technician orients Kai instead of small-talking. This
  // is the only guidance the first loop gets: no quest, no marker, just a
  // colonist explaining what her machine needs and where it might come from.
  if (s.roleAnchor?.role === 'fabricator') {
    return {
      settlerId: s.id,
      name: s.name,
      speciesLabel: 'Fabrication technician',
      affinity,
      firstMeeting,
      lines: technicianLines(world, s, firstMeeting),
    };
  }

  const lines: DialogueLine[] = [{ speaker: s.name, text: greetingLine(s, affinity, firstMeeting) }];

  // A guarded settler says one line and no more.
  if (affinity > -10 || firstMeeting) {
    const goal = goalLine(s, world);
    if (goal) lines.push({ speaker: s.name, text: goal });
    const color = colorLine(s, world, affinity);
    if (color && lines.length < 3) lines.push({ speaker: s.name, text: color });
  }

  return {
    settlerId: s.id,
    name: s.name,
    speciesLabel: `${speciesDef.name} settler`,
    affinity,
    firstMeeting,
    lines,
  };
}

/** Ambient one-liners shown above autonomously conversing pairs. */
const AMBIENT_TOPICS = [
  'about the water',
  'about the glowing plants',
  'about what to build first',
  'about the ridge',
  'about the ones who stayed behind',
  'about the night sky',
  'about food',
];

/** Deterministic per-pair ambient snippet (no RNG, so it is stable per pair). */
export function ambientChatter(aId: string, bId: string, startedAt: number): string {
  let h = 0;
  const key = aId < bId ? aId + bId : bId + aId;
  for (let i = 0; i < key.length; i++) h = (h * 31 + key.charCodeAt(i)) | 0;
  h = (h + Math.floor(startedAt)) | 0;
  return AMBIENT_TOPICS[Math.abs(h) % AMBIENT_TOPICS.length];
}
